### ISSUE TITLE
Daemon mode shows "Unexpected Command Error"

### ISSUE THREAD

**Issue by t1m0thyj** [zowe/zowe-cli#1081]
**Current Behavior:**
```
$ zowe files ls ds SYS1.PARMLIB --host XXX --port 443 --user YYY --password ZZZ --base-path abc
Command Error:
z/OSMF REST API Error:
Rest API failure with HTTP(S) status 404
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"><html><head><title>404 Not Found</title></head><body><h1>Not Found</h1><p>The application or context root for this request has not been found: &#047;abc&#047;zosmf&#047;restfiles&#047;ds</p></body></html>
Error Details:
HTTP(S) error status "404" received.
Review request details (resource, base path, credentials, payload) and ensure correctness.

Protocol:  https
Host:      XXX
Port:      1443
Base Path: abc
Resource:  /zosmf/restfiles/ds?dslevel=SYS1.PARMLIB
Request:   GET
Headers:   [{"Accept-Encoding":"gzip"},{"X-IBM-Max-Items":"0"},{"X-CSRF-ZOSMF-HEADER":true}]
Payload:   undefined

$ zowex files ls ds SYS1.PARMLIB --host XXX --port 1443 --user YYY --password ZZZ --base-path abc
Unexpected Command Error:
Please review the message and stack below.
Contact the creator of handler:
"c:\Users\tj891237\Projects\zowe-next\zowe-cli\packages\cli\lib\zosfiles\list\ds\DataSet.handler"
Message:
z/OSMF REST API Error:
Rest API failure with HTTP(S) status 404
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"><html><head><title>404 Not Found</title></head><body><h1>Not Found</h1><p>The application or context root for this request has not been found: &#047;abc&#047;zosmf&#047;restfiles&#047;ds</p></body></html>
Stack:
Error: z/OSMF REST API Error:
Rest API failure with HTTP(S) status 404
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"><html><head><title>404 Not Found</title></head><body><h1>Not Found</h1><p>The application or context root for this request has not been found: &#047;abc&#047;zosmf&#047;restfiles&#047;ds</p></body></html>
    at ZosmfRestClient.populateError (C:\Users\tj891237\Projects\zowe-next\imperative\lib\rest\src\client\AbstractRestClient.js:521:16)
    at ZosmfRestClient.onEnd (C:\Users\tj891237\Projects\zowe-next\imperative\lib\rest\src\client\AbstractRestClient.js:437:31)
    at IncomingMessage.<anonymous> (C:\Users\tj891237\Projects\zowe-next\imperative\lib\rest\src\client\AbstractRestClient.js:363:18)
    at IncomingMessage.emit (events.js:387:35)
    at endReadableNT (internal/streams/readable.js:1317:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
```

**Expected Behavior:** The error output in daemon mode should be identical to the error message produced without daemon mode.

**Comment by t1m0thyj** [comment]
Another example of different (less informative) messages occurs when Keytar fails to load:
```
$ zowe profiles create zosmf test --host XXX --port 123 --user XXX --password XXX
Command Error:
Unable to store the secure field "user" associated with the profile "test" of type "zosmf".
Error Details:
Keytar not Installed

$ ./zowex profiles create zosmf test --host XXX --port 123 --user XXX --password XXX
Command Preparation Failed:
Keytar not Installed
```

**Comment by t1m0thyj** [comment]
Error messages in comments 1 and 3 appear to have been fixed, but I can still reproduce the inconsistent message in comment 2.
