### ISSUE TITLE
 zowe zos-jobs list spool-files-by-jobid

### ISSUE THREAD

**Issue by hammyau** [zowe/zowe-cli#1085]
Hi All, playing around with zowe cli. Which in general seems great.

Entered 

```zowe zos-jobs list spool-files-by-jobid 10715```

Gets a stack dump
Message:
item.trim is not a function
```
Stack:
TypeError: item.trim is not a function
    at Function.toBeDefinedAndNonBlank (...AppData\Roaming\npm\node_modules\@zowe\cli\node_modules\@zowe\imperative\lib\expect\src\ImperativeExpect.js:211:18)
    at Function.<anonymous> (...AppData\Roaming\npm\node_modules\@zowe\cli\lib\zosjobs\src\api\GetJobs.js:105:43)
    at Generator.next (<anonymous>)
    at ...AppData\Roaming\npm\node_modules\@zowe\cli\lib\zosjobs\src\api\GetJobs.js:18:71
    at new Promise (<anonymous>)
    at __awaiter (...AppData\Roaming\npm\node_modules\@zowe\cli\lib\zosjobs\src\api\GetJobs.js:14:12)
    at Function.getJob (...AppData\Roaming\npm\node_modules\@zowe\cli\lib\zosjobs\src\api\GetJobs.js:103:16)
    at SpoolFilesHandler.<anonymous> (...AppData\Roaming\npm\node_modules\@zowe\cli\lib\zosjobs\src\cli\list\spool-files-by-jobid\SpoolFilesByJobid.handler.js:41:49)
    at Generator.next (<anonymous>)
    at ...AppData\Roaming\npm\node_modules\@zowe\cli\lib\zosjobs\src\cli\list\spool-files-by-jobid\SpoolFilesByJobid.handler.js:18:71
```

Tried

```zowe zos-jobs list spool-files-by-jobid JOB10750```

All good I can see the spool list.

Probably should handle the syntax error more gracefully? 

Cheers,
Ian

**Comment by hammyau** [comment]
That is running on Widows 10.

```
$ zowe -V
6.22.0
```

**Comment by hammyau** [comment]
Sorry those job numbers should be the same. It is the lack of "JOB" in the jobid that is the issue.

**Comment by KevinLoesch1** [comment]
This was fixed in the base imparative functionality. [](https://github.com/zowe/imperative/issues/856)
