### ISSUE TITLE
Example in Zowe Node.js Client SDK documentation use deprecated code

### ISSUE THREAD

**Issue by plavjanik** [zowe/zowe-cli#1141]
For example, https://docs.zowe.org/stable/typedoc/modules/_zowe_zos_jobs_for_zowe_sdk.html has this code:

```
    ...
    const session: Session = ZosmfSession.createBasicZosmfSession(defaultZosmfProfile);
    ...
```

Which produces following warning:
```
The signature '(profile: IProfile): Session' of 'ZosmfSession.createBasicZosmfSession' is deprecated.ts(6387)
ZosmfSession.d.ts(48, 8): The declaration was marked as deprecated here.
```

What is the recommended alternative that is not deprecated?

**Comment by plavjanik** [comment]
My goal is to easily load and use the profile information that is used in the CLI.

**Comment by inv9wj1** [comment]
I am facing the same issue in fixing this, if anyone can able to help, pls do. 
Below code snippet where i am trying to replace the with new api version of zowe v2. But i am getting error. 
 Could anyone pls compare the old code with new code and help me, what is the mistake i make here pls?

Old code:

const zowe = require('@zowe/cli')
let userTSO = process.env.MF_USER_TSO;
let paramsTSO = {};
const host = process.env.MF_HOST;
const port = process.env.MF_PORT;
const user = process.env.MF_USER_ZOS;
const password = process.env.MF_PASSWORD;
const profile = {
    host, port, user, password, rejectUnauthorized: false
}

const session = zowe.ZosmfSession.createBasicZosmfSessionFromArguments(profile);
    try {
        let response = await zowejobs.DownloadJobs.downloadAllSpoolContentCommon(session, jobParms);
        // console.log(response); // this is always undefined
    } catch (err) {
        console.log("error in DOWNLOADing files:");
        console.log(err)
        // res.status(400).json(err);
        return ({status: "error", message: err});
    }


New code:

const zowe = require('@zowe/cli')
let userTSO = process.env.MF_USER_TSO;
let paramsTSO = {};
const host = process.env.MF_HOST;
const port = process.env.MF_PORT;
const user = process.env.MF_USER_ZOS;
const password = process.env.MF_PASSWORD;
const profile = {
    host, port, user, password, rejectUnauthorized: false
}

const session = zowe.ZosmfSession.createSessCfgFromArgs(profile);
    try {
        let response = await zowejobs.DownloadJobs.downloadAllSpoolContentCommon(session, jobParms);
        // console.log(response); // this is always undefined
    } catch (err) {
        console.log("error in DOWNLOADing files:");
        console.log(err)
        // res.status(400).json(err);
        return ({status: "error", message: err});
    }


Error received :
Inside MF router get /getbulletin
req.body:  {}
Callinggg --------------------------------------------------
after Callinggg --------------------------------------------------[object Object]
TypeError: Cannot read property 'hostname' of undefined
    at ZosmfRestClient.buildOptions (C:\Rajesh Files\personal\GANESH FILES\prod\server_v3\node_modules\@zowe\imperative\lib\rest\src\client\AbstractRestClient.js:261:45)
    at Promise (C:\Rajesh Files\personal\GANESH FILES\prod\server_v3\node_modules\@zowe\imperative\lib\rest\src\client\AbstractRestClient.js:117:39)
    at new Promise (<anonymous>)
    at ZosmfRestClient.request (C:\Rajesh Files\personal\GANESH FILES\prod\server_v3\node_modules\@zowe\imperative\lib\rest\src\client\AbstractRestClient.js:95:16)
    at Function.postExpectString (C:\Rajesh Files\personal\GANESH FILES\prod\server_v3\node_modules\@zowe\imperative\lib\rest\src\client\RestClient.js:226:34)
    at Function.<anonymous> (C:\Rajesh Files\personal\GANESH FILES\prod\server_v3\node_modules\@zowe\imperative\lib\rest\src\client\RestClient.js:88:37)
    at Generator.next (<anonymous>)
    at C:\Rajesh Files\personal\GANESH FILES\prod\server_v3\node_modules\@zowe\imperative\lib\rest\src\client\RestClient.js:18:71   
    at new Promise (<anonymous>)
    at __awaiter (C:\Rajesh Files\personal\GANESH FILES\prod\server_v3\node_modules\@zowe\imperative\lib\rest\src\client\RestClient.js:14:12)
GET /mf/getbulletin 500 31.050 ms - 2
Inside MF router get /mf/getjoblist
TypeError: Cannot read property 'hostname' of undefined
    at ZosmfRestClient.buildOptions (C:\Rajesh Files\personal\GANESH FILES\prod\server_v3\node_modules\@zowe\imperative\lib\rest\src\client\AbstractRestClient.js:261:45)
    at Promise (C:\Rajesh Files\personal\GANESH FILES\prod\server_v3\node_modules\@zowe\imperative\lib\rest\src\client\AbstractRestClient.js:117:39)
    at new Promise (<anonymous>)
    at ZosmfRestClient.request (C:\Rajesh Files\personal\GANESH FILES\prod\server_v3\node_modules\@zowe\imperative\lib\rest\src\client\AbstractRestClient.js:95:16)
    at Function.getExpectString (C:\Rajesh Files\personal\GANESH FILES\prod\server_v3\node_modules\@zowe\imperative\lib\rest\src\client\RestClient.js:196:34)
    at Function.<anonymous> (C:\Rajesh Files\personal\GANESH FILES\prod\server_v3\node_modules\@zowe\imperative\lib\rest\src\client\RestClient.js:50:37)
    at Generator.next (<anonymous>)
    at C:\Rajesh Files\personal\GANESH FILES\prod\server_v3\node_modules\@zowe\imperative\lib\rest\src\client\RestClient.js:18:71   
    at new Promise (<anonymous>)
    at __awaiter (C:\Rajesh Files\personal\GANESH FILES\prod\server_v3\node_modules\@zowe\imperative\lib\rest\src\client\RestClient.js:14:12)
GET /mf/getjoblist 500 42.440 ms - 32
