### ISSUE TITLE
zos-file invoke ams-file error "Maximum call stack size exceeded"

### ISSUE THREAD

**Issue by pjfarleyiii** [zowe/zowe-cli#1293]
Trying to execute an AMS command to display contents of a large catalog generates error "Maximum call stack size exceeded".  Response output below.

CMD.EXE environment under Windows 10 Pro Version 21H2

C:\testdir>zowe --version
6.37.0
C:\testdir>zowe files call af listcat.ams.cat  1>listcat.cat.out

Sample of input AMS file:

```
  PARM GRAPHICS(CHAIN(TN))
  LISTCAT CATALOG('LARGE.CATALOG') ALL
```
zowe response:

```
Unexpected Command Error:
Please review the message and stack below.
Contact the creator of handler:
"C:\Users\Peter\AppData\Roaming\npm\node_modules\@zowe\cli\lib\zosfiles\invoke\amsFile\AmsFile.handler"
Message:
Maximum call stack size exceeded
Stack:
RangeError: Maximum call stack size exceeded
    at C:\Users\Peter\AppData\Roaming\npm\node_modules\@zowe\cli\node_modules\prettyjson\lib\prettyjson.js:167:19
    at Array.forEach (<anonymous>)
    at renderToArray (C:\Users\Peter\AppData\Roaming\npm\node_modules\@zowe\cli\node_modules\prettyjson\lib\prettyjson.js:145:36)
    at Object.render (C:\Users\Peter\AppData\Roaming\npm\node_modules\@zowe\cli\node_modules\prettyjson\lib\prettyjson.js:210:10)
    at Function.prettyJson (C:\Users\Peter\AppData\Roaming\npm\node_modules\@zowe\cli\node_modules\@zowe\imperative\lib\utilities\src\TextUtils.js:120:27)
    at AmsFileHandler.<anonymous> (C:\Users\Peter\AppData\Roaming\npm\node_modules\@zowe\cli\lib\zosfiles\invoke\amsFile\AmsFile.handler.js:34:75)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\Peter\AppData\Roaming\npm\node_modules\@zowe\cli\lib\zosfiles\invoke\amsFile\AmsFile.handler.js:15:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

**Comment by t1m0thyj** [comment]
The `prettyjson` package that Zowe CLI uses to render its output appears to handle large JSON objects poorly: https://github.com/rafeca/prettyjson/issues/43

As the linked issue has been dormant for nearly 3 years, we may need to look for an alternative dependency.
