### ISSUE TITLE
Zowe Daemon - Error: listen EADDRINUSE

### ISSUE THREAD

**Issue by dkelosky** [zowe/zowe-cli#1378]
Is there any fallback option for tcpip socket (similar to docker) or some other workaround?

When running the new daemon client I get:
```
C:\dev\node\zowe-cli\zowex>zowe --daemon
Error: listen EADDRINUSE: address already in use \\.\pipe\xxxx\ZoweDaemon
    at Server.setupListenHandle [as _listen2] (net.js:1301:21)
    at listenInCluster (net.js:1366:12)
    at Server.listen (net.js:1463:5)
    at DaemonDecider.runOrUseDaemon (C:\dev\node\zowe-cli\packages\cli\lib\daemon\DaemonDecider.js:70:26)
    at C:\dev\node\zowe-cli\packages\cli\lib\main.js:50:23
    at Generator.next (<anonymous>)
    at fulfilled (C:\dev\node\zowe-cli\packages\cli\lib\main.js:16:58)
Command Error:
listen EADDRINUSE: address already in use \\.\pipe\xxxx\ZoweDaemon
Imperative encountered an unexpected exception
Command entered: "zowe --daemon"
Use "zowe --daemon undefined --help" to view groups, commands, and options.
Error Details:
listen EADDRINUSE: address already in use \\.\pipe\xxxx\ZoweDaemon
```

**Comment by dkelosky** [comment]
welp - after restarting my computer, I cannot get this problem to occur any more 😄. this is all working good.
