### ISSUE TITLE
Zowe CLI V2 - Using environment variables in profile properties

### ISSUE THREAD

**Issue by FALLAI-Denis** [zowe/zowe-cli#1425]
Hi,

I would like to use environment variables in properties of managed profiles in `zowe.config.json` or `zowe.config.user.json`, especially for SSH type profile.

I am in Windows environment.

I tried:
```
{
    "$schema": "./zowe.schema.json",
    "profiles": {
        "GMVS-SSH": {
            "type": "ssh",
            "properties": {
                "host": "GMVS",
                "port": 22,
                "user": "J%AGENT%",
                "privateKey": "%USERPROFILE%\\.ssh\\id_rsa"
            },
            "secure": [
                "password"
            ]
        },
}
```
I got:
```
$ zowe uss issue command "pwd"
Unexpected Command Error:
Please review the message and stack below.
Contact the creator of handler:
"C:\ProgramData\nvm\v12.13.0\node_modules\@zowe\cli\lib\zosuss\issue\ssh/Ssh.handler"
Message:
ENOENT: no such file or directory, open '%USERPROFILE%\.ssh\id_rsa'
Stack:
Error: ENOENT: no such file or directory, open '%USERPROFILE%\.ssh\id_rsa'
    at Object.openSync (fs.js:440:3)
    at Object.readFileSync (fs.js:342:35)
    at C:\ProgramData\nvm\v12.13.0\node_modules\@zowe\cli\node_modules\@zowe\zos-uss-for-zowe-sdk\lib\Shell.js:145:35
    at new Promise (<anonymous>)
    at Function.executeSsh (C:\ProgramData\nvm\v12.13.0\node_modules\@zowe\cli\node_modules\@zowe\zos-uss-for-zowe-sdk\lib\Shell.js:30:25)
    at Handler.<anonymous> (C:\ProgramData\nvm\v12.13.0\node_modules\@zowe\cli\lib\zosuss\issue\ssh\Ssh.handler.js:38:57)
    at Generator.next (<anonymous>)
    at C:\ProgramData\nvm\v12.13.0\node_modules\@zowe\cli\lib\zosuss\issue\ssh\Ssh.handler.js:18:71
    at new Promise (<anonymous>)
    at __awaiter (C:\ProgramData\nvm\v12.13.0\node_modules\@zowe\cli\lib\zosuss\issue\ssh\Ssh.handler.js:14:12)
```

I also tried:
```
{
    "$schema": "./zowe.schema.json",
    "profiles": {
        "GMVS-SSH": {
            "type": "ssh",
            "properties": {
                "host": "GMVS",
                "port": 22,
                "user": "J%AGENT%",
                "privateKey": "~/.ssh/id_rsa"
            },
            "secure": [
                "password"
            ]
        },
}
```
I got:
```
$ zowe uss issue command "pwd"
Unexpected Command Error:
Please review the message and stack below.
Contact the creator of handler:
"C:\ProgramData\nvm\v12.13.0\node_modules\@zowe\cli\lib\zosuss\issue\ssh/Ssh.handler"
Message:
ENOENT: no such file or directory, open '~/.ssh/id_rsa'
Stack:
Error: ENOENT: no such file or directory, open '~/.ssh/id_rsa'
    at Object.openSync (fs.js:440:3)
    at Object.readFileSync (fs.js:342:35)
    at C:\ProgramData\nvm\v12.13.0\node_modules\@zowe\cli\node_modules\@zowe\zos-uss-for-zowe-sdk\lib\Shell.js:145:35
    at new Promise (<anonymous>)
    at Function.executeSsh (C:\ProgramData\nvm\v12.13.0\node_modules\@zowe\cli\node_modules\@zowe\zos-uss-for-zowe-sdk\lib\Shell.js:30:25)
    at Handler.<anonymous> (C:\ProgramData\nvm\v12.13.0\node_modules\@zowe\cli\lib\zosuss\issue\ssh\Ssh.handler.js:38:57)
    at Generator.next (<anonymous>)
    at C:\ProgramData\nvm\v12.13.0\node_modules\@zowe\cli\lib\zosuss\issue\ssh\Ssh.handler.js:18:71
    at new Promise (<anonymous>)
    at __awaiter (C:\ProgramData\nvm\v12.13.0\node_modules\@zowe\cli\lib\zosuss\issue\ssh\Ssh.handler.js:14:12)
```

Is it possible to use environment variables in profile properties? and if yes, how?

Thanks.

**Comment by gejohnston** [comment]
The Zowe CLI does not currently have a feature to interpret environment variables placed within a profile. This seems like a valid enhancement request. It is not clear if and when such an enhancement could be prioritized and implemented.

To address your needs with currently existing technology, perhaps we need to brainstorm some techniques. One possibility is the use of the V2 'user' config, in which each user could specify his/her own privateKey property, which could be hardcoded for each user. That has the downside that each user must provide his/her own property value. Further thought may lead to other possible techniques.

**Comment by gejohnston** [comment]
I may be missing some special behavior that you are trying to accomplish, but let me describe how we recommend using zowe.config.json and zowe.config.user.json.

You create zowe.config.json at the root of your Git repo. The contents of this file is to be shared with all project team members. This file is commited to Git and thus is available to all project team members.

Each user also creates zowe.config.user.json at the root of your Git repo. This file can be a very small subset of the possible properties that you place in zowe.config.json. In fact, you would only place those properties that differ for that particular user into zowe.config.user.json. To ensure that the private values of zowe.config.user.json are not accidentally committed and shared with other team members, you add zowe.config.user.json to your .gitignore file at the root of your Git repo.

I only mention our "recommended practice" to ensure that you do not accidentally take the wrong approach with your V2 configuration. It does not diminish the value of your enhancement request for environment variables in the configuration file. If that capability existed, you might only need zowe.config.json (with environment variables), and have no zowe.config.user.json at all in your project. 

In case you are not aware, you can have both zowe.config.json and zowe.config.user.json in your $ZOWE_CLI_HOME directory (which is ~/.zowe by default) and both can also reside in your Git project directory at the same time. Some rules for merging the property values must be understood, but such a set of multiple config files is valid. The values found in ~/.zowe/zowe.config.json are used for every directory, except a directory that contains a zowe.config.json file, in which case the values in the project directory override the values from the ~/.zowe/zowe.config.json file. The same rules apply to zowe.config.user.json.

Regarding your earlier comment about recognizing ~/somefile in a profile: As your experiments have shown the ~ character is also not processed by Zowe CLI. Personally (one man's opinion), I feel that it would be a more robust solution to implement environment variables than to attempt to interpret the ~ character.

**Comment by FALLAI-Denis** [comment]
Hi @gejohnston,

I thought I had given you the results of my last tests, but apparently not...

I succeed to get the expected result:

.gitignore (extract):
```
# - Profils Zowe Utilisateur
zowe.config.user.json
```

zowe.config.json (extract):
```
        "GMVS-SSH": {
            "type": "ssh",
            "properties": {
                "host": "GMVS",
                "port": 22
            },
            "secure": [
                "password"
            ]
        },
```

zowe.config.user.json.sample-copy-not-rename (extract): tracked by Git
```
        "GMVS-SSH": {
            "properties": {
                "user": "<remote_user>",
                "privateKey": "C:\\Users\\<local_user>\\.ssh\\id_rsa"
            }
        }
```

zowe.config.user.json (extract): not tracked by Git
```
        "GMVS-SSH": {
            "properties": {
                "user": "J070188",
                "privateKey": "C:\\Users\\S0070188\\.ssh\\id_rsa"
            }
        }
```

**Comment by FALLAI-Denis** [comment]
Another question: if there is a zowe.config[.user].json file present in the Workspace, is the same zowe.config[.user].json file present in the home directory also took into consideration ?

**Comment by gejohnston** [comment]
You are correct. Global, project, team, and user config files do affect your result. Values in one will override values from another. I have used the following diagram in presentations to explain how that occurs. I hope that the diagram will explain it better than if I type in a bunch of words.

![image](https://user-images.githubusercontent.com/37119146/169582240-7012147a-aeba-4b13-a029-e09cac356140.png)

**Comment by gejohnston** [comment]
I have an idea about why your partial SSH profile in your user config does not contribute to the SSH profile from your team config file. I want to experiment a bit to confirm my idea, so that I do not inadvertently mislead you. I will follow-up when I have some results.

**Comment by FALLAI-Denis** [comment]
Hi @gejohnston,

Thanks for your answers.

I solved my problem for SSH profile as illustrated above.

**Comment by FALLAI-Denis** [comment]
Hi,

I get the impression that managing of secure properties depends on the location of the zowe.config[.user].json file and not just the profile name.

If I have the same profile name in my config file in my home directory and in a config file placed in my workspace, depending on where I issue my zowe command from, at the first time I use the profile, secure information will be prompted and possibly stored.

**Comment by FALLAI-Denis** [comment]
Hi @gejohnston,

For me a profile identifier must be absolute and independent of any context:
* the identifier of a profile must not be dependent on the internal organization of the `zowe.config[.user].json` file, cf. #1413 
* the storage of secure information must be independent of the location of the `zowe.config[.user].json` file

With Zowe V1, all users had to declare the profiles used, and these profiles were attached to their user code and their workstation, (use of home directory to strore profiles declaration).
This was the source of many errors on their part and we (solution administrators) had no control over this.

With Zowe V2, we decided to relieve the user of any profile declaration.
Profiles are directly integrated into our Git Repositories, depending on the needs of the Application contained in the Git Repository, and therefore in the VS Code Workspace.
We thus control profile identifiers (which allows us to hard code them in configuration files or procedures), and we eliminate all reporting errors.

We will manage more than 1000 Git repositories for our System. Each user will only use a small number, but still around ten.
However, we only have 3 development z/OS partitions (an some others for production), so we only have 3 series of profiles, and all the profiles addressing the same z/OS partition always have the same identifiers, and for the user they will always have the same credentials.
Each time the user changes Git Repository, therefore Workspace, therefore `zowe.config[.user].json` file, he will have to provide these credentials again, whereas these are only linked to the z/OS partition, and are independent of the Git Repository / Workspace / `zowe.config[.user].json` file.

There is therefore an inconsistency in the profile management architecture with Zowe V2:
* profile declarations can be shared between users by placing the `zowe.config[.user].json` file in the Workspace, but this involves multiplying the contexts of the credentials
* we can share the contexts of credentials, but this involves multiplying the declarations of `zowe.config[.user].json` files in the users' home directories

We want a solution that makes it possible to share profile declarations between users, and which also makes it possible to pool credentials management contexts.

Perhaps it would be necessary to introduce into the profile management scheme, a notion of credentials attachment key.
Something like:

```
"secure": {
    "keyContext": "my_context_which_can_be_the_lpar_id",
    "properties": [
      "user",
      "password"
    ],
}
```

All secure properties are shared between profiles that declare the same context key.

**Comment by zFernand0** [comment]
The original enhancement request is still valid.
Let's wait to see if we get enough 👍🏽 on this issue.

Enhancement request:
Support environment variables within a `zowe.config.json`
```json
{
    "$schema": "./zowe.schema.json",
    "profiles": {
        "ssh": {
            "type": "ssh",
            "properties": {
                "host": "my.host.net",
                "port": 42,
                "user": "%USER%",
                "privateKey": "%HOMEPATH%\\.ssh\\id_rsa"
            },
        },
}
```
