### ISSUE TITLE
root user getting on CentOS - Error: EACCES: permission denied, mkdir '/root/.zowe/'

### ISSUE THREAD

**Issue by dkelosky** [zowe/zowe-cli#180]
Here is the full log - do I need to do anything else prior to running in root?
```
[root@<USER>-T20241 ~]# npm install -g @brightside/core@2.0.0-next.201901181325
npm WARN deprecated circular-json@0.5.9: CircularJSON is in maintenance only, flatted is its successor.
/usr/bin/zowe -> /usr/lib/node_modules/@brightside/core/lib/main.js
/usr/bin/bright -> /usr/lib/node_modules/@brightside/core/lib/main.js

> @brightside/core@2.0.0-next.201901181325 postinstall /usr/lib/node_modules/@brightside/core
> node ./scripts/validatePlugins

Since you re-installed Zowe CLI, we are re-validating any plugins.
[2019/01/22 10:01:83] [DEBUG] Writting all logged messages in memory to /usr/lib/node_modules/@brightside/core/imperative_debug.log
[2019/01/22 10:01:83] [INFO] Error: EACCES: permission denied, open '/usr/lib/node_modules/@brightside/core/imperative_debug.log'
[2019/01/22 10:01:83] [INFO] Error: EACCES: permission denied, open '/usr/lib/node_modules/@brightside/core/imperative_debug.log'
[2019/01/22 10:01:83] [FATAL] [Imperative.js:184] { Error: EACCES: permission denied, mkdir '/root/.zowe/'
    at Object.mkdirSync (fs.js:753:3)
    at Function.createDirSync (/usr/lib/node_modules/@brightside/core/node_modules/@brightside/imperative/lib/io/src/IO.js:77:16)
    at Function.createDirsSync (/usr/lib/node_modules/@brightside/core/node_modules/@brightside/imperative/lib/io/src/IO.js:96:16)
    at Function.createDirsSyncFromFilePath (/usr/lib/node_modules/@brightside/core/node_modules/@brightside/imperative/lib/io/src/IO.js:110:12)
    at settings_1.AppSettings.initialize (/usr/lib/node_modules/@brightside/core/node_modules/@brightside/imperative/lib/imperative/src/Imperative.js:307:16)
    at new AppSettings (/usr/lib/node_modules/@brightside/core/node_modules/@brightside/imperative/lib/settings/src/AppSettings.js:47:28)
    at Function.initialize (/usr/lib/node_modules/@brightside/core/node_modules/@brightside/imperative/lib/settings/src/AppSettings.js:80:33)
    at Function.initAppSettings (/usr/lib/node_modules/@brightside/core/node_modules/@brightside/imperative/lib/imperative/src/Imperative.js:302:32)
    at Function.<anonymous> (/usr/lib/node_modules/@brightside/core/node_modules/@brightside/imperative/lib/imperative/src/Imperative.js:104:22)
    at Generator.next (<anonymous>)
  errno: -13,
  syscall: 'mkdir',
  code: 'EACCES',
  path: '/root/.zowe/' }
[2019/01/22 10:01:83] [INFO] Error: EACCES: permission denied, open '/usr/lib/node_modules/@brightside/core/imperative_debug.log'
[2019/01/22 10:01:83] [FATAL] [Imperative.js:186] Diagnostic information:
Platform: 'linux', Architecture: 'x64', Process.argv: '/usr/bin/node /usr/lib/node_modules/@brightside/core/scripts/validatePlugins plugins validate'
Node versions: '{
  "http_parser": "2.8.0",
  "node": "10.15.0",
  "v8": "6.8.275.32-node.45",
  "uv": "1.23.2",
  "zlib": "1.2.11",
  "ares": "1.15.0",
  "modules": "64",
  "nghttp2": "1.34.0",
  "napi": "3",
  "openssl": "1.1.0j",
  "icu": "62.1",
  "unicode": "11.0",
  "cldr": "33.1",
  "tz": "2018e"
}'Environmental variables: '{
  "npm_config_save_dev": "",
  "npm_config_legacy_bundling": "",
  "npm_config_dry_run": "",
  "npm_config_viewer": "man",
  "npm_config_only": "",
  "npm_config_commit_hooks": "true",
  "npm_config_browser": "",
  "npm_package_jest_coverageDirectory": "<rootDir>/__tests__/__results__/unit/coverage",
  "npm_package_devDependencies_dataobject_parser": "^1.1.3",
  "npm_package_repository": "",
  "npm_config_also": "",
  "npm_package_deprecated": "false",
  "npm_package_publishConfig_registry": "https://api.bintray.com/npm/ca/brightside",
  "XDG_SESSION_ID": "46",
  "npm_config_sign_git_commit": "",
  "npm_config_rollback": "true",
  "npm_package_devDependencies_jest_environment_node_debug": "^2.0.0",
  "npm_package_bin_bright": "./lib/main.js",
  "HOSTNAME": "<USER>-T20241",
  "NODE": "/usr/bin/node",
  "npm_config_usage": "",
  "npm_config_audit": "true",
  "SELINUX_ROLE_REQUESTED": "",
  "INIT_CWD": "/root",
  "npm_package_jest_testEnvironment": "node",
  "npm_package_devDependencies_typescript": "^2.6.2",
  "npm_package_devDependencies_sinon": "3.2.1",
  "npm_config_globalignorefile": "/usr/etc/npmignore",
  "npm_package_devDependencies_madge": "3.2.0",
  "npm_package_devDependencies_jest": "^22.4.3",
  "SHELL": "/bin/bash",
  "TERM": "cygwin",
  "npm_config_shell": "/bin/bash",
  "npm_config_maxsockets": "50",
  "npm_config_init_author_url": "",
  "npm_package_devDependencies_rimraf": "2.6.2",
  "npm_package_devDependencies_jest_junit": "^3.6.0",
  "HISTSIZE": "1000",
  "TMPDIR": "/usr/lib/node_modules/@brightside/core",
  "npm_config_shrinkwrap": "true",
  "npm_config_parseable": "",
  "npm_config_metrics_registry": "https://registry.npmjs.org/",
  "npm_package_jest_html_reporter_outputPath": "__tests__/__results__/results.html",
  "npm_package_devDependencies_tslint": "5.10.0",
  "SSH_CLIENT": "10.137.179.137 59656 22",
  "npm_config_timing": "",
  "npm_config_init_license": "ISC",
  "npm_package_scripts_typedocSpecifySrc": "typedoc --options ./typedoc.json",
  "npm_package_scripts_lint": "npm run lint:packages && npm run lint:tests",
  "npm_package_scripts_installWithBuild": "npm install && npm run build",
  "npm_config_if_present": "",
  "npm_package_devDependencies_fs_extra": "^7.0.0",
  "npm_package_devDependencies__types_chai": "^4.0.1",
  "npm_package_bin_zowe": "./lib/main.js",
  "SELINUX_USE_CURRENT_RANGE": "",
  "npm_config__brightside_registry": "https://api.bintray.com/npm/ca/brightside",
  "npm_package_jest_html_reporter_pageTitle": "Zowe CLI Tests",
  "npm_config_sign_git_tag": "",
  "npm_config_init_author_email": "",
  "npm_config_cache_max": "Infinity",
  "npm_package_jest_setupTestFrameworkScriptFile": "./__tests__/beforeTests.js",
  "QTDIR": "/usr/lib64/qt-3.3",
  "npm_config_preid": "",
  "npm_config_long": "",
  "npm_config_local_address": "",
  "npm_config_git_tag_version": "true",
  "npm_config_cert": "",
  "QTINC": "/usr/lib64/qt-3.3/include",
  "npm_config_registry": "https://registry.npmjs.org/",
  "npm_config_noproxy": "",
  "npm_config_fetch_retries": "2",
  "npm_package_devDependencies_jest_html_reporter": "^0.5.7",
  "npm_package_devDependencies_codepage": "^1.10.1",
  "npm_package_dependencies_js_yaml": "3.9.0",
  "SSH_TTY": "/dev/pts/0",
  "npm_package_devDependencies_sinon_chai": "2.13.0",
  "npm_config_versions": "",
  "npm_config_message": "%s",
  "npm_config_key": "",
  "npm_package_jest_watchPathIgnorePatterns_0": ".*jest-stare.*\\.js",
  "npm_package_devDependencies_gulp_plumber": "^1.1.0",
  "QT_GRAPHICSSYSTEM_CHECKED": "1",
  "npm_package_description": "CA Brightside is a command line interface (CLI) that provides a simple and streamlined way to interact with IBM z/OS.",
  "USER": "root",
  "npm_package_jest_collectCoverage": "false",
  "npm_package_devDependencies__types_js_yaml": "^3.11.1",
  "npm_package_devDependencies__types_chai_string": "^1.1.30",
  "npm_package_license": "EPL-2.0",
  "LS_COLORS": "rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=01;05;37;41:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.axv=01;35:*.anx=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=01;36:*.au=01;36:*.flac=01;36:*.mid=01;36:*.midi=01;36:*.mka=01;36:*.mp3=01;36:*.mpc=01;36:*.ogg=01;36:*.ra=01;36:*.wav=01;36:*.axa=01;36:*.oga=01;36:*.spx=01;36:*.xspf=01;36:",
  "LD_LIBRARY_PATH": "/opt/CA/SharedComponents/lib:/opt/CA/CAlib:/opt/CA/DSM/caf/lib",
  "CA_ITRM_BASEDIR": "/opt/CA/DSM",
  "npm_config_globalconfig": "/usr/etc/npmrc",
  "npm_config_prefer_online": "",
  "npm_config_logs_max": "10",
  "npm_config_always_auth": "",
  "npm_package_devDependencies__types_yargs": "8.0.2",
  "npm_package_dependencies__brightside_imperative": ">=2.0.0-0",
  "npm_package_jest_transform___ts_": "ts-jest",
  "npm_package_devDependencies_clear_require": "^2.0.0",
  "npm_package_devDependencies__types_jest": "^22.2.3",
  "npm_execpath": "/usr/lib/node_modules/npm/bin/npm-cli.js",
  "npm_config_global_style": "",
  "npm_config_cache_lock_retries": "10",
  "npm_package_scripts_generateCleanTypedoc": "npm run typedoc && gulp cleanTypedoc",
  "npm_config_update_notifier": "true",
  "npm_config_cafile": "",
  "npm_package_scripts_test_cleanUpProfiles": "sh __tests__/__scripts__/clean_profiles.sh",
  "npm_package_devDependencies_glob": "^7.1.2",
  "npm_package_scripts_doc_generate": "npm run doc:clean && npm run typedoc && gulp doc",
  "npm_package_author_name": "CA",
  "npm_config_heading": "npm",
  "npm_config_audit_level": "low",
  "npm_package_devDependencies_gulp_util": "^3.0.8",
  "npm_config_searchlimit": "20",
  "npm_config_read_only": "",
  "npm_config_offline": "",
  "npm_config_fetch_retry_mintimeout": "10000",
  "npm_config_json": "",
  "npm_config_access": "",
  "npm_config_argv": "{\"remain\":[\"@brightside/core@2.0.0-next.201901181325\"],\"cooked\":[\"install\",\"--global\",\"@brightside/core@2.0.0-next.201901181325\"],\"original\":[\"install\",\"-g\",\"@brightside/core@2.0.0-next.201901181325\"]}",
  "npm_package_devDependencies_uuid": "^3.2.1",
  "npm_package_scripts_postinstall": "node ./scripts/validatePlugins",
  "PATH": "/usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/usr/lib/node_modules/@brightside/core/node_modules/.bin:/usr/lib/node_modules/.bin:/usr/lib64/qt-3.3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/opt/CA/SharedComponents/bin:/opt/CA/SharedComponents/ccs/cam/bin:/root/bin",
  "MAIL": "/var/spool/mail/root",
  "CA_LOCALE": "enu",
  "npm_config_allow_same_version": "",
  "npm_package_devDependencies_typedoc": "^0.11.1",
  "npm_package_devDependencies_prompt": "1.0.0",
  "npm_package_devDependencies_jest_stare": "1.6.0",
  "CA_CAILANGUAGE": "enu",
  "npm_config_https_proxy": "",
  "npm_config_engine_strict": "",
  "npm_config_description": "true",
  "npm_package_jest_testRegex": "__tests__.*\\.(spec|test)\\.ts$",
  "npm_package_devDependencies_through2": "^2.0.3",
  "_": "/usr/bin/node",
  "npm_config_userconfig": "/root/.npmrc",
  "npm_config_init_module": "/root/.npm-init.js",
  "npm_package_devDependencies_ts_jest": "^22.4.2",
  "npm_package_devDependencies_gulp_debug": "^3.1.0",
  "npm_package_keywords_4": "z/OSMF",
  "DMPRIMER_DIR": "/opt/CA/DSM/dmprimer",
  "npm_config_cidr": "",
  "npm_package_keywords_5": "mvs",
  "PWD": "/usr/lib/node_modules/@brightside/core",
  "npm_config_user": "nobody",
  "npm_config_node_version": "10.15.0",
  "npm_package_jest_junit_output": "__tests__/__results__/junit.xml",
  "npm_package_devDependencies__types_lodash": "^4.14.106",
  "npm_package_keywords_6": "os390",
  "CA_DSM_CONFIGDATA": "/opt/CA/DSM",
  "npm_lifecycle_event": "postinstall",
  "npm_package_devDependencies_chai": "^4.1.2",
  "npm_package_keywords_7": "z/OS",
  "npm_config_save": "true",
  "npm_config_ignore_prepublish": "",
  "npm_config_editor": "vi",
  "npm_config_auth_type": "legacy",
  "npm_package_jest_stare_coverageLink": "../unit/coverage/lcov-report/index.html",
  "npm_package_jest_collectCoverageFrom_3": "!**/main.ts",
  "npm_package_devDependencies_shebang_regex": "^2.0.0",
  "npm_package_imperative_configurationModule": "lib/imperative.js",
  "npm_package_keywords_0": "zosmf",
  "npm_package_name": "@brightside/core",
  "LANG": "en_US.UTF-8",
  "npm_config_tag": "latest",
  "npm_config_script_shell": "",
  "npm_package_jest_collectCoverageFrom_2": "!packages/**/doc/I*.ts",
  "npm_package_scripts_test_integration": "cross-env FORCE_COLOR=1 jest \".*__tests__.*\\.integration\\.(spec|test)\\.ts\" --coverage false",
  "npm_package_keywords_1": "mainframe",
  "npm_config_progress": "true",
  "npm_config_global": "true",
  "npm_package_bundleDependencies": "false",
  "npm_package_jest_collectCoverageFrom_1": "!**/__tests__/**",
  "npm_package_scripts_build": "gulp updateLicense && tsc --pretty && npm run lint && npm run checkTestsCompile && madge -c lib",
  "npm_package_keywords_2": "CLI",
  "KDEDIRS": "/usr",
  "npm_config_searchstaleness": "900",
  "npm_config_optional": "true",
  "npm_config_ham_it_up": "",
  "npm_package_jest_collectCoverageFrom_0": "packages/**/*.ts",
  "npm_package_devDependencies_jest_environment_node": "^22.4.3",
  "npm_package_scripts_lint_packages": "tslint --format stylish -c ./tslint-packages.json \"packages/**/*.ts\"",
  "npm_package_keywords_3": "zos",
  "npm_config_save_prod": "",
  "npm_config_force": "",
  "npm_config_bin_links": "true",
  "npm_package_scripts_checkTestsCompile": "echo \"Checking that test source compiles...\" && tsc --project __tests__/test-tsconfig.json --noEmit ",
  "SELINUX_LEVEL_REQUESTED": "",
  "npm_config_searchopts": "",
  "npm_package_engines_node": ">=6.0.0",
  "npm_package_devDependencies_chai_string": "^1.4.0",
  "npm_config_node_gyp": "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js",
  "npm_config_depth": "Infinity",
  "npm_package_main": "lib/index.js",
  "npm_config_sso_poll_frequency": "500",
  "npm_config_rebuild_bundle": "true",
  "npm_package_devDependencies_gulp_cli": "^2.0.1",
  "npm_package_scripts_watch": "tsc --pretty --watch",
  "npm_package_scripts_lint_tests": "tslint --format stylish -c ./tslint-tests.json \"**/__tests__/**/*.ts\"",
  "npm_package_version": "2.0.0-next.201901181325",
  "HISTCONTROL": "ignoredups",
  "ITRMENV_CALLED": "true",
  "npm_config_unicode": "true",
  "npm_package_jestSonar_reportPath": "__tests__/__results__/jest-sonar",
  "npm_package_devDependencies_strip_ansi": "^4.0.0",
  "npm_package_keywords_8": "zowe",
  "HOME": "/root",
  "SHLVL": "2",
  "npm_config_fetch_retry_maxtimeout": "60000",
  "npm_package_devDependencies_jest_sonar_reporter": "2.0.0",
  "npm_package_scripts_watch_test": "jest --watch",
  "npm_package_scripts_test": "npm run test:unit && npm run test:integration && npm run test:system",
  "CANOLOG_flag": "",
  "npm_config_tag_version_prefix": "v",
  "npm_config_strict_ssl": "true",
  "npm_config_sso_type": "oauth",
  "npm_config_scripts_prepend_node_path": "warn-only",
  "npm_config_save_prefix": "^",
  "npm_config_loglevel": "notice",
  "npm_config_ca": "",
  "npm_package_devDependencies_cpx": "^1.5.0",
  "npm_config_save_exact": "",
  "npm_config_group": "",
  "npm_config_fetch_retry_factor": "10",
  "npm_config_dev": "",
  "npm_package_devDependencies_gulp": "^4.0.0",
  "npm_package_devDependencies_cross_env": "^5.1.4",
  "npm_config_version": "",
  "npm_config_prefer_offline": "",
  "npm_config_cache_lock_stale": "60000",
  "npm_config_otp": "",
  "npm_config_cache_min": "10",
  "npm_package_jest_globals_ts_jest_disableSourceMapSupport": "true",
  "npm_package_devDependencies_ts_node": "^3.3.0",
  "npm_config_searchexclude": "",
  "npm_config_cache": "/root/.npm",
  "npm_package_typings": "lib/index.d.ts",
  "LOGNAME": "root",
  "npm_lifecycle_script": "node ./scripts/validatePlugins",
  "npm_config_color": "true",
  "QTLIB": "/usr/lib64/qt-3.3/lib",
  "npm_config_proxy": "",
  "npm_config_package_lock": "true",
  "npm_package_jest_stare_additionalResultsProcessors_2": "jest-sonar-reporter",
  "npm_package_jest_modulePathIgnorePatterns_0": "__tests__/__snapshots__/",
  "SSH_CONNECTION": "10.137.179.137 59656 10.242.84.77 22",
  "npm_config_package_lock_only": "",
  "npm_package_jest_stare_additionalResultsProcessors_1": "jest-html-reporter",
  "npm_package_jest_moduleFileExtensions_1": "js",
  "npm_package_devDependencies__types_sinon": "2.3.3",
  "npm_config_save_optional": "",
  "npm_package_jest_stare_additionalResultsProcessors_0": "jest-junit",
  "npm_package_jest_moduleFileExtensions_0": "ts",
  "LESSOPEN": "||/usr/bin/lesspipe.sh %s",
  "npm_config_ignore_scripts": "",
  "npm_config_user_agent": "npm/6.4.1 node/v10.15.0 linux x64",
  "npm_package_devDependencies_jsonfile": "^4.0.0",
  "CASHCOMP": "/opt/CA/SharedComponents",
  "npm_config_cache_lock_wait": "10000",
  "npm_package_devDependencies_jest_cli": "^22.4.3",
  "npm_package_devDependencies_gulp_replace": "^0.6.1",
  "npm_package_devDependencies__types_node": "8.0.28",
  "npm_package_devDependencies_chalk": "2.3.0",
  "npm_package_files_2": "scripts",
  "CAI_MSQ": "/opt/CA/SharedComponents/ccs/cam",
  "SDROOT": "/opt/CA/DSM/sd",
  "npm_config_production": "",
  "npm_package_jest_stare_resultDir": "__tests__/__results__/jest-stare",
  "npm_package_scripts_test_system": "cross-env FORCE_COLOR=1 jest \".*__tests__.*\\.system\\.(spec|test)\\.ts\" --coverage false",
  "npm_package_files_1": "docs",
  "XDG_RUNTIME_DIR": "/run/user/0",
  "npm_config_send_metrics": "",
  "npm_config_save_bundle": "",
  "npm_package_dependencies_string_width": "2.1.1",
  "npm_package_files_0": "lib",
  "QT_PLUGIN_PATH": "/usr/lib64/kde4/plugins:/usr/lib/kde4/plugins",
  "CABIN": "/opt/CA/SharedComponents/bin",
  "npm_config_umask": "0022",
  "npm_config_node_options": "",
  "npm_config_init_version": "1.0.0",
  "npm_package_jest_coverageReporters_3": "cobertura",
  "npm_package_jest_testResultsProcessor": "jest-stare",
  "npm_package_scripts_typedoc": "typedoc --options ./typedoc.json ./packages/",
  "CA_DSM_FAILOVER_STATE": "1",
  "CA_DSM_LANG": "en_US.UTF-8",
  "npm_config_init_author_name": "",
  "npm_config_git": "git",
  "npm_config_scope": "",
  "npm_package_jest_coverageReporters_2": "text",
  "npm_package_scripts_audit_public": "npm audit --registry https://registry.npmjs.org/",
  "CALIB": "/opt/CA/SharedComponents/lib",
  "npm_config_unsafe_perm": "",
  "npm_config_tmp": "/tmp",
  "npm_config_onload_script": "",
  "npm_package_jest_coverageReporters_1": "lcov",
  "npm_package_scripts_doc_clean": "gulp cleanTypedoc && rimraf docs/CLIReadme.md",
  "npm_package_scripts_test_cleanResults": "rimraf __tests__/__results__",
  "npm_node_execpath": "/usr/bin/node",
  "npm_config_prefix": "/usr",
  "npm_config_link": "",
  "npm_package_jest_coverageReporters_0": "json",
  "npm_package_scripts_test_unit": "cross-env FORCE_COLOR=1 jest \".*__tests__.*\\.unit\\.(spec|test)\\.ts\" --coverage"
}'
[2019/01/22 10:01:83] [INFO] Error: EACCES: permission denied, open '/usr/lib/node_modules/@brightside/core/imperative_debug.log'
[2019/01/22 10:01:84] [FATAL] [main.js:26] Error initializing CA Brightside:
 { Error: UNEXPECTED ERROR ENCOUNTERED
    at Function.<anonymous> (/usr/lib/node_modules/@brightside/core/node_modules/@brightside/imperative/lib/imperative/src/Imperative.js:197:21)
    at Generator.next (<anonymous>)
    at /usr/lib/node_modules/@brightside/core/node_modules/@brightside/imperative/lib/imperative/src/Imperative.js:17:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/lib/node_modules/@brightside/core/node_modules/@brightside/imperative/lib/imperative/src/Imperative.js:13:12)
    at Promise (/usr/lib/node_modules/@brightside/core/node_modules/@brightside/imperative/lib/imperative/src/Imperative.js:87:78)
    at new Promise (<anonymous>)
    at Function.init (/usr/lib/node_modules/@brightside/core/node_modules/@brightside/imperative/lib/imperative/src/Imperative.js:87:16)
    at Object.<anonymous> (/usr/lib/node_modules/@brightside/core/lib/main.js:21:39)
    at Generator.next (<anonymous>)
  mDetails:
   { msg: 'UNEXPECTED ERROR ENCOUNTERED',
     causeErrors:
      { Error: EACCES: permission denied, mkdir '/root/.zowe/'
          at Object.mkdirSync (fs.js:753:3)
          at Function.createDirSync (/usr/lib/node_modules/@brightside/core/node_modules/@brightside/imperative/lib/io/src/IO.js:77:16)
          at Function.createDirsSync (/usr/lib/node_modules/@brightside/core/node_modules/@brightside/imperative/lib/io/src/IO.js:96:16)
          at Function.createDirsSyncFromFilePath (/usr/lib/node_modules/@brightside/core/node_modules/@brightside/imperative/lib/io/src/IO.js:110:12)
          at settings_1.AppSettings.initialize (/usr/lib/node_modules/@brightside/core/node_modules/@brightside/imperative/lib/imperative/src/Imperative.js:307:16)
          at new AppSettings (/usr/lib/node_modules/@brightside/core/node_modules/@brightside/imperative/lib/settings/src/AppSettings.js:47:28)
          at Function.initialize (/usr/lib/node_modules/@brightside/core/node_modules/@brightside/imperative/lib/settings/src/AppSettings.js:80:33)
          at Function.initAppSettings (/usr/lib/node_modules/@brightside/core/node_modules/@brightside/imperative/lib/imperative/src/Imperative.js:302:32)
          at Function.<anonymous> (/usr/lib/node_modules/@brightside/core/node_modules/@brightside/imperative/lib/imperative/src/Imperative.js:104:22)
          at Generator.next (<anonymous>)
        errno: -13,
        syscall: 'mkdir',
        code: 'EACCES',
        path: '/root/.zowe/' } },
  mMessage: 'UNEXPECTED ERROR ENCOUNTERED' }
+ @brightside/core@2.0.0-next.201901181325
added 555 packages from 827 contributors and updated 1 package in 12.751s
```

**Comment by ChrisBoehmCA** [comment]
I think your options would be to add permissions for the root user for /root/.zowe or set 
 the ZOWE_CLI_HOME environmental variable to a directory that root can already access.  Not sure of the exact commands for the first option. Maybe something like (As root): 
`chown root /root/.zowe` ?

**Comment by AHumanFromCA** [comment]
This appears to be a problem with the plugin facility validating any installed plugins. It tries to run the command and fails on the log file and then tries to write to a directory that root doesn't have proper access to. This is currently a problem on all Linux OSs, and is probably the direct cause of #181 that you have just opened.

If it is alright with you, I think we should mark #181 as a duplicate of this one and track all the fix progress here.

**Comment by AHumanFromCA** [comment]
Also looks like the root failure was this `mkdir /root/.zowe/` could you see if you could create that directory yourself as root to possibly remove permission problems.

**Comment by dkelosky** [comment]
@AHumanFromCA I opened #181 for the unhandled promise, it seemed like it was a separate issue, but if you think they should be combined that sounds fine

**Comment by dkelosky** [comment]
@AHumanFromCA I tried to create the directory:
```
[root@<USER>-T20241 ~]# mkdir /root/.zowe
mkdir: cannot create directory ‘/root/.zowe’: File exists
```

**Comment by dkelosky** [comment]
It looks like I get the #181 behavior:
```
[root@<USER>-T20241 ~]# npm install -g @brightside/core@2.0.0-next.201901181325
npm WARN deprecated circular-json@0.5.9: CircularJSON is in maintenance only, flatted is its successor.
/usr/bin/zowe -> /usr/lib/node_modules/@brightside/core/lib/main.js
/usr/bin/bright -> /usr/lib/node_modules/@brightside/core/lib/main.js

> @brightside/core@2.0.0-next.201901181325 postinstall /usr/lib/node_modules/@brightside/core
> node ./scripts/validatePlugins

Since you re-installed Zowe CLI, we are re-validating any plugins.
(node:8011) UnhandledPromiseRejectionWarning: Error: EACCES: permission denied, open '/root/.zowe/imperative/logs/imperative.log'
    at Object.openSync (fs.js:439:3)
    at Object.writeFileSync (fs.js:1190:35)
    at Object.appendFileSync (fs.js:1236:6)
    at writeTheChunk (/usr/lib/node_modules/@brightside/core/node_modules/log4js/lib/appenders/fileSync.js:118:10)
    at RollingFileSync.write (/usr/lib/node_modules/@brightside/core/node_modules/log4js/lib/appenders/fileSync.js:129:5)
    at /usr/lib/node_modules/@brightside/core/node_modules/log4js/lib/appenders/fileSync.js:183:13
    at categoryAppenders.forEach (/usr/lib/node_modules/@brightside/core/node_modules/log4js/lib/log4js.js:42:5)
    at Array.forEach (<anonymous>)
    at sendLogEventToAppender (/usr/lib/node_modules/@brightside/core/node_modules/log4js/lib/log4js.js:41:21)
    at listeners.forEach.l (/usr/lib/node_modules/@brightside/core/node_modules/log4js/lib/clustering.js:16:26)
(node:8011) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:8011) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
+ @brightside/core@2.0.0-next.201901181325
updated 2 packages in 23.787s
```

**Comment by dkelosky** [comment]
`npm install -g @brightside/core@2.0.0-next.201901181325 --unsafe-perm` with the `--unsafe-perm` flag causes the message to go away.  The flag is documented [here](https://docs.npmjs.com/misc/config#unsafe-perm)

Although, it makes you feel uneasy installed something and specifying `unsafe` in that process :thinking: ...

**Comment by dkelosky** [comment]
Another alternative to suppressing errors is to use the `--ignore-scripts` setting, e.g. `npm install -g @brightside/core@2.0.0-next.201901181325 --ignore-scripts`.  It seems from the documentation that the `--unsafe-perm` is geared towards `root` users and preventing `postinstall` scripts from running automatically with `root` authority.

It seems like `"postinstall": "node ./scripts/validatePlugins",` is the culprit causing the behavior (is exposing the unhandled promise rejection for #181).  

@AHumanFromCA Is `validatePlugins` pure validation?  Or, is it doing other work that must run and be successful prior to using the CLI or plugins?  If the former, perhaps this should not be an automatic `postinstall` script?

**Comment by AHumanFromCA** [comment]
I would say that validate is necessary. It checks to see that the plugin will work and our CLI still functions after installing a plugin. I believe it can save some headaches by having it run automatically.

**Comment by MikeBauerCA** [comment]
We should provide guidance on installing as root and the behavior of such an installation in the short term. @dkelosky could you open a separate enhancement request for allowing multiple users to share only plugins.

**Comment by dkelosky** [comment]
I opened #225

**Comment by dkelosky** [comment]
sharing link from @tucker01 as a recommended way install on linux:
https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally

I'll close this now in favor of that doc.

Thanks
