### ISSUE TITLE
Issue with npm installing modules for subpackages

### ISSUE THREAD

**Issue by adam-wolfe** [zowe/zowe-cli#1846]
**Edit: This issue was caused by using an invalid version of NPM (9.2.0 in this case). The issue was resolved by updating NPM to 9.4.2 or above.**

**Describe the bug**

When attempting to build the CLI from the master branch with a fresh clone, the `npm install` step will fail with the message:
```
> prepare
> husky install && npm run bundle:webHelp

husky - Git hooks installed

> bundle:webHelp
> cd packages/imperative/web-help && node build.js

compiling web help bundle.....node:internal/modules/cjs/loader:1039
  const err = new Error(message);
              ^

Error: Cannot find module 'postcss-url'
Require stack:
- C:\Users\me\GitRepos\zowe-cli\packages\imperative\web-help\build.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1039:15)
    at Module._load (node:internal/modules/cjs/loader:885:27)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at postcssTransform (C:\Users\me\GitRepos\zowe-cli\packages\imperative\web-help\build.js:52:24)
    at concatFiles (C:\Users\me\GitRepos\zowe-cli\packages\imperative\web-help\build.js:44:47)
    at async Promise.all (index 2) {
  code: 'MODULE_NOT_FOUND',
```
You must run `npm install` first in the packages/imperative/web-help directory first. After that you can build the CLI package normally.

**Expected and actual results**

**Describe your environment**

**Additional context**

**Comment by adam-wolfe** [comment]
This was caused by the version of NPM that I had installed. Updating NPM resolved the issue.
