### ISSUE TITLE
VS Code Plugin not working

### ISSUE THREAD

**Issue by jelaplan** [zowe/zowe-cli#433]
I get an error when trying to use the VS Code Plugin.

Error attempting to load the default zosmf profile for Zowe CLI. Please ensure that you have created at least one profile with Zowe CLI before attempting to use this extension. 
**Note**: I have a profile. I can use the CLI to manually list data sets etc. 

Error text:(node:31937) UnhandledPromiseRejectionWarning: 

Error: An error occurred collecting all configurations from the profile root directory "/Users/lapjo01/.zowe/profiles". Please supply the configurations on the profile manager constructor parameters OR initialize the profile manager environment. 

Details: Profile IO Error: Error reading profile file ("/Users/lapjo01/.zowe/profiles/.DS_Store/.DS_Store_meta.yaml")
**Note:** .DS_Store is a file in my file system - not a directory.

. Error Details: ENOTDIR: not a directory, open '/Users/lapjo01/.zowe/profiles/.DS_Store/.DS_Store_meta.yaml'
    at new AbstractProfileManager (/Users/lapjo01/.vscode/extensions/zowe.vscode-extension-for-zowe-0.17.0/node_modules/@brightside/imperative/lib/profiles/src/abstract/AbstractProfileManager.js:106:23)
    at new BasicProfileManager (/Users/lapjo01/.vscode/extensions/zowe.vscode-extension-for-zowe-0.17.0/node_modules/@brightside/imperative/lib/profiles/src/BasicProfileManager.js:47:1)
    at new CliProfileManager (/Users/lapjo01/.vscode/extensions/zowe.vscode-extension-for-zowe-0.17.0/node_modules/@brightside/imperative/lib/cmd/src/profiles/CliProfileManager.js:32:1)
    at Object.<anonymous> (/Users/lapjo01/.vscode/extensions/zowe.vscode-extension-for-zowe-0.17.0/out/src/getDefaultProfile.js:34:33)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/lapjo01/.vscode/extensions/zowe.vscode-extension-for-zowe-0.17.0/out/src/getDefaultProfile.js:14:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:757:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
(node:31937) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:31937) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by jelaplan** [comment]
We can temporarily fix this problem by deleting the file named .zowe/profiles/.DS_Store. But then that file gets recreated by some unclear means. It seems that the zowe CLI is looking at that file as a directory or as a kind of profile and is getting an error because it isn't a directory but rather a file. Maybe we can ignore that file name or ignore files in general.

**Comment by jelaplan** [comment]
I think that @ChrisBoehmCA has found a way to address this problem.

**Comment by ChrisBoehmCA** [comment]
Yes I put in a fix which should ignore the DS_STORE file. https://github.com/zowe/imperative/pull/220 However somebody needs to update the vscode extension to use a new version of Zowe CLI that has this new Imperative version included.  @zFernand0, @Colin-Stone,  or @tjohnsonBCM should be able to update when this fix is available on Bintray. Thanks

**Comment by Colin-Stone** [comment]
I can pick this up later today with another PR I am doing

**Comment by ChrisBoehmCA** [comment]
OK Thanks. I'm not 100% sure if that fix has been deployed to bintray yet. Might need to merge the next PR into lts-incremental to get it to. @zFernand0  could probably figure out whether it has or not

**Comment by zFernand0** [comment]
It's on Bintray today.
Thank you very much @ChrisBoehmCA for still answering questions 👍

**Comment by tjohnsonBCM** [comment]
Fix was published in Imperative 2.4.6 and has made it into the VS Code extension
