### ISSUE TITLE
Required parameter 'original' must not be blank

### ISSUE THREAD

**Issue by dkelosky** [zowe/zowe-cli#473]
```
C:\dev\node>zowe --version
5.9.1
```

I get the following error when downloading content on job submission:
```
C:\Users\xxx\Desktop>zowe jobs submit ds "xxx.work.jcl(asmtest1)" -d test
 ███████___| 70%  o | Downloading spool content for JOB02024, CC 0000Error: Expect Error: Required parameter 'original' must not be blank
    at Function.toBeDefinedAndNonBlank (C:\Users\xxx\AppData\Roaming\npm\node_modules\@zowe\cli\node_modules\@zowe\imperative\lib\expect\src\ImperativeExpect.js:212:19)
    at Function.processNewlines (C:\Users\xxx\AppData\Roaming\npm\node_modules\@zowe\cli\node_modules\@zowe\imperative\lib\io\src\IO.js:211:35)
    at ZosmfRestClient.onData (C:\Users\xxx\AppData\Roaming\npm\node_modules\@zowe\cli\node_modules\@zowe\imperative\lib\rest\src\client\AbstractRestClient.js:353:48)
    at IncomingMessage.res.on (C:\Users\xxx\AppData\Roaming\npm\node_modules\@zowe\cli\node_modules\@zowe\imperative\lib\rest\src\client\AbstractRestClient.js:323:18)
    at IncomingMessage.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at IncomingMessage.Readable.push (_stream_readable.js:224:10)
    at HTTPParser.parserOnBody (_http_common.js:122:22)
    at TLSSocket.socketOnData (_http_client.js:442:20)
Command Error:
z/OSMF REST API Error:
http(s) request error event called
Error: Parse Error
Error Details:
HTTP(S) client encountered an error. Request could not be initiated to host.
Review connection details (host, port) and ensure correctness.

Host:      usildamd.lvn.broadcom.net
Port:      443
Base Path:
Resource:  /zosmf/restjobs/jobs/XXXXXXX$/JOB02024/files/101/records
Request:   GET
Headers:   [{"X-CSRF-ZOSMF-HEADER":true}]
Payload:   undefined
Command Error:
Expect Error: Required parameter 'original' must not be blank
Imperative encountered an unexpected exception
Command entered: "zowe jobs submit ds xxx.work.jcl(asmtest1) --d test"
Use "zowe jobs submit --help" to view groups, commands, and options.
Error Details:
Expect Error: Required parameter 'original' must not be blank
```

**Comment by tucker01** [comment]
Looks like its getting data chunks that are just spaces (perfectly valid) and the imperative expect is checking for non-blank.

This is a defect. Thanks for opening.
