### ISSUE TITLE
VS Code Error attempting to load the default zosmf profile for Zowe CLI

### ISSUE THREAD

**Issue by spufidoo** [zowe/zowe-cli#484]
Trying to get the ZOWE Extension for VS Code working, I get the following error upon startup:

Error attempting to load the default zosmf profile for Zowe CLI. Please ensure that you have created at least one profile with Zowe CLI before attempting to use this extension. Error text:(node:31088) UnhandledPromiseRejectionWarning: Error: No default profile set for type "zosmf".
    at CliProfileManager.<anonymous> (C:\Users\mdavage\.vscode\extensions\zowe.vscode-extension-for-zowe-0.22.0\node_modules\@brightside\imperative\lib\profiles\src\abstract\AbstractProfileManager.js:341:27)
    at Generator.next (<anonymous>)
    at C:\Users\mdavage\.vscode\extensions\zowe.vscode-extension-for-zowe-0.22.0\node_modules\@brightside\imperative\lib\profiles\src\abstract\AbstractProfileManager.js:17:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\mdavage\.vscode\extensions\zowe.vscode-extension-for-zowe-0.22.0\node_modules\@brightside\imperative\lib\profiles\src\abstract\AbstractProfileManager.js:13:12)
    at CliProfileManager.load (C:\Users\mdavage\.vscode\extensions\zowe.vscode-extension-for-zowe-0.22.0\node_modules\@brightside\imperative\lib\profiles\src\abstract\AbstractProfileManager.js:318:16)
    at Object.<anonymous> (C:\Users\mdavage\.vscode\extensions\zowe.vscode-extension-for-zowe-0.22.0\out\src\getDefaultProfile.js:37:8)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\mdavage\.vscode\extensions\zowe.vscode-extension-for-zowe-0.22.0\out\src\getDefaultProfile.js:14:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:31088) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:31088) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Yet I have set a default profile in the ZOWE CLI, which performs perfectly well from the command line.

**Comment by spufidoo** [comment]
Reopened, because it is different from 433.

**Comment by MatthewB19** [comment]
@spufidoo Did you, by any chance, install zowe-cli on WSL?

If so, you may need to install the VSC Zowe Extension on WSL instead of on Windows.

**Comment by awharn** [comment]
This issue is over 2 years old and appears to be working properly using the current version of Zowe CLI and the VS Code Extension, and is being closed. If this is still an issue, please feel free to re-open the issue.
