### ISSUE TITLE
Issuing --help-web causes error

### ISSUE THREAD

**Issue by ChrisBoehmCA** [zowe/zowe-cli#500]
node --version
v10.16.0

npm --version
6.9.0

`zowe jobs sub ds --hw`
Generating web help(node:1064) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type object
    at validateString (internal/validators.js:125:11)
    at Object.join (path.js:427:7)
    at WebHelpGenerator.buildHelp (C:\Users\xxxxx\AppData\Roaming\npm\node_modules\@zowe\cli\node_modules\@zowe\imperative\lib\cmd\src\help\WebHelpGenerator.js:46:30)
    at WebHelpManager.openHelp (C:\Users\xxx\AppData\Roaming\npm\node_modules\@zowe\cli\node_modules\@zowe\imperative\lib\cmd\src\help\WebHelpManager.js:50:17)
    at CommandYargs.executeWebHelp (C:\Users\xxx\AppData\Roaming\npm\node_modules\@zowe\cli\node_modules\@zowe\imperative\lib\cmd\src\yargs\AbstractCommandYargs.js:205:50)
    at CommandYargs.<anonymous> (C:\Users\xxx\AppData\Roaming\npm\node_modules\@zowe\cli\node_modules\@zowe\imperative\lib\cmd\src\yargs\CommandYargs.js:113:22)
    at Generator.next (<anonymous>)
    at C:\Users\xxx\AppData\Roaming\npm\node_modules\@zowe\cli\node_modules\@zowe\imperative\lib\cmd\src\yargs\CommandYargs.js:17:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\xxx\AppData\Roaming\npm\node_modules\@zowe\cli\node_modules\@zowe\imperative\lib\cmd\src\yargs\CommandYargs.js:13:12)
(node:1064) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1064) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by gejohnston** [comment]
This is a known problem. It was fixed in imperative PR#262 : Bug copying webhelp dist 
The CLI version 5.14.1-alpha.201908051621 fixes this problem.
It can be installed from the daily tag:
    npm install -g @zowe/cli@daily

Once it is independently validated, this fix will be promoted to @latest.

**Comment by dogboydog** [comment]
Thanks, that fixed it for me.
