### ISSUE TITLE
Fails to download job output if a DD is empty

### ISSUE THREAD

**Issue by ChrisBoehmCA** [zowe/zowe-cli#664]
Hello, 

I think in Imperative, "processNewLines" is expecting a non blank string. However, it's okay if the content of a DD is blank. I would just like a blank file to be created. Maybe this ImperativeExpect statement could be relaxed to allow empty content. 

I thought this was fixed in #218 but maybe it was re-introduced when I refactored the streaming RestClient stuff

A fix for this would help me with our CI pipelines : ) 

`zowe --version`
5.14.1-alpha.201908051621

`zowe jobs download output STCxxxx --directory ./spool` 
Command Error:
z/OSMF REST API Error:
http(s) request error event called
Error: Parse Error
Error Details:
HTTP(S) client encountered an error. Request could not be initiated to host.
Review connection details (host, port) and ensure correctness.

Host:      xxxx
Port:     xxxxx
Base Path: 
Resource:  /zosmf/restjobs/jobs/xxx/xxx/files/105/records
Request:   GET
Headers:   [{"X-CSRF-ZOSMF-HEADER":true}]
Payload:   undefined
Error: Expect Error: Required parameter 'original' must not be blank
    at Function.toBeDefinedAndNonBlank (C:\Users\Administrator\AppData\Roaming\npm\node_modules\@zowe\cli\node_modules\@zowe\imperative\lib\expect\src\ImperativeExpect.js:212:19)
    at Function.processNewlines (C:\Users\Administrator\AppData\Roaming\npm\node_modules\@zowe\cli\node_modules\@zowe\imperative\lib\io\src\IO.js:211:35)
    at ZosmfRestClient.onData (C:\Users\Administrator\AppData\Roaming\npm\node_modules\@zowe\cli\node_modules\@zowe\imperative\lib\rest\src\client\AbstractRestClient.js:353:48)
    at IncomingMessage.res.on (C:\Users\Administrator\AppData\Roaming\npm\node_modules\@zowe\cli\node_modules\@zowe\imperative\lib\rest\src\client\AbstractRestClient.js:323:18)
    at IncomingMessage.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at IncomingMessage.Readable.push (_stream_readable.js:224:10)
    at HTTPParser.parserOnBody (_http_common.js:122:22)
    at TLSSocket.socketOnData (_http_client.js:442:20)
Command Error:
Expect Error: Required parameter 'original' must not be blank
Imperative encountered an unexpected exception

**Comment by ChrisBoehmCA** [comment]
Looks like this was already fixed in https://github.com/zowe/imperative/pull/267
