### ISSUE TITLE
EACCES: permission denied, mkdir '/root/.zowe/

### ISSUE THREAD

**Issue by mvillegasgh** [zowe/zowe-cli#827]
Hello, 

While Installing zowe cli on centOS 7 machine, I got this error. 

I tried to solve the issue using the root user and manually changing the npm default directory, but I still get the same error, links below:

_

- https://github.com/zowe/zowe-cli/issues/180
- https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally

_

**LOG:**

_16:39:13 [2020/09/25 09:09:03] [INFO] Error: EACCES: permission denied, open '/usr/lib/node_modules/@zowe/cli/imperative_debug.log'
16:39:13 [2020/09/25 09:09:04] [FATAL] [main.js:48] Error initializing Zowe CLI:
16:39:13  { Error: UNEXPECTED ERROR ENCOUNTERED
16:39:13     at Function.<anonymous> (/usr/lib/node_modules/@zowe/cli/node_modules/@zowe/imperative/lib/imperative/src/Imperative.js:226:21)
16:39:13     at Generator.next (<anonymous>)
16:39:13     at /usr/lib/node_modules/@zowe/cli/node_modules/@zowe/imperative/lib/imperative/src/Imperative.js:18:71
16:39:13     at new Promise (<anonymous>)
16:39:13     at __awaiter (/usr/lib/node_modules/@zowe/cli/node_modules/@zowe/imperative/lib/imperative/src/Imperative.js:14:12)
16:39:13     at Promise (/usr/lib/node_modules/@zowe/cli/node_modules/@zowe/imperative/lib/imperative/src/Imperative.js:105:78)
16:39:13     at new Promise (<anonymous>)
16:39:13     at Function.init (/usr/lib/node_modules/@zowe/cli/node_modules/@zowe/imperative/lib/imperative/src/Imperative.js:105:16)
16:39:13     at /usr/lib/node_modules/@zowe/cli/lib/main.js:38:39
16:39:13     at Generator.next (<anonymous>)
16:39:13   mDetails: 
16:39:13    { msg: 'UNEXPECTED ERROR ENCOUNTERED',
16:39:13      causeErrors: 
16:39:13       { Error: EACCES: permission denied, mkdir '/root/.zowe/'
16:39:13     at Object.fs.mkdirSync (fs.js:885:18)
16:39:13     at Function.createDirSync (/usr/lib/node_modules/@zowe/cli/node_modules/@zowe/imperative/lib/io/src/IO.js:77:16)
16:39:13     at Function.createDirsSync (/usr/lib/node_modules/@zowe/cli/node_modules/@zowe/imperative/lib/io/src/IO.js:96:16)
16:39:13     at Function.createDirsSyncFromFilePath (/usr/lib/node_modules/@zowe/cli/node_modules/@zowe/imperative/lib/io/src/IO.js:110:12)
16:39:13     at Function.initialize (/usr/lib/node_modules/@zowe/cli/node_modules/@zowe/imperative/lib/settings/src/AppSettings.js:54:25)
16:39:13     at Function.initAppSettings (/usr/lib/node_modules/@zowe/cli/node_modules/@zowe/imperative/lib/imperative/src/Imperative.js:346:32)
16:39:13     at Function.<anonymous> (/usr/lib/node_modules/@zowe/cli/node_modules/@zowe/imperative/lib/imperative/src/Imperative.js:127:22)
16:39:13     at Generator.next (<anonymous>)
16:39:13     at /usr/lib/node_modules/@zowe/cli/node_modules/@zowe/imperative/lib/imperative/src/Imperative.js:18:71
16:39:13     at new Promise (<anonymous>)
16:39:13         errno: -13,
16:39:13         code: 'EACCES',
16:39:13         syscall: 'mkdir',
16:39:13         path: '/root/.zowe/' } },
16:39:13   mMessage: 'UNEXPECTED ERROR ENCOUNTERED' }_

**Comment by ChrisBoehmCA** [comment]
Hi,

The .zowe folder is controller by Zowe CLI and not NPM so changing the NPM directory won't help with this specific issue. There is a workaround for this here: 

https://github.com/zowe/zowe-cli#frequently-asked-questions

The /root/.zowe folder doesn't need to exist if you are not going to use the CLI as root so the --ignore-scripts flag will skip trying to create that.

**Comment by gejohnston** [comment]
This issue appears to be related to file & directory rights for users in the operating system on this computer. This issue has had no activity for 12 months, so I am closing it.
